PREFIX : <https://www.uxmethods.org/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?URI a :WebResource;
    dc:title ?title;
    dc:creator ?creator;
    dc:publisher ?publisher;
    dc:created ?date;
    :resourceLocation ?resourceURL;
    dc:created ?date;
    :describes ?describesIRI.
}
FROM <https://docs.google.com/spreadsheets/d/19cAHQNoICjCjOOMDMgvBlRRY7c_L5EC0FG8pzqNLkzk/export?format=csv&id=19cAHQNoICjCjOOMDMgvBlRRY7c_L5EC0FG8pzqNLkzk&gid=1896378389>
WHERE {
  BIND (URI(CONCAT('https://www.uxmethods.org/', ?id)) AS ?URI)
  BIND (xsd:anyURI(?url) AS ?resourceURL)
  BIND (xsd:date(?created) AS ?date)
  BIND (URI(CONCAT('https://www.uxmethods.org/', ?describes)) AS ?describesIRI)
}
